version: 0.2

phases:
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - echo Building Docker image...
      - docker build -t nodeapp .
      - docker tag nodeapp:latest 714732271094.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
      - echo Pushing Docker image to Amazon ECR...
      - docker push 714732271094.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest

