version: 0.2

phases:
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 714732271094.dkr.ecr.us-east-1.amazonaws.com
      - echo Building Docker image.....
      - docker build -t nodeapp .
      - docker tag nodeapp:latest 714732271094.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
      - echo Pushing Docker image to Amazon ECR...
      - docker push 714732271094.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest

